### ISSUE TITLE
"LiveAPIEvent" is not defined

### ISSUE THREAD

**Issue by HarryOYY** [zeejayym/apex-liveapi-documentation#1]
When I run your code I never receive anything. Think it's because the 'LiveAPIEvent' object that you assign 'incoming' to on line 11 is not being found:
![image](https://github.com/zeejayym/apex-liveapi-documentation/assets/58606595/701e6d27-59fe-4578-bd58-16e0dcb9b07d)

I run the following and I will receive the init message from Apex at the very least:
https://gist.github.com/HarryOYY/ea63bc1524f9a5ce6fa262c79d73c79e

What class is this supposed to be coming from?

**Comment by zeejayym** [comment]
```shell
protoc --proto_path="<LiveAPI directory>" --python_out="<target directory>" events.proto
```
Located here:

**Comment by zeejayym** [comment]
It also looks like you possibly don't have websockets installed on your environment. Make sure you install it in case it's not.
```shell
python -m pip install websockets
```

The `LiveAPIEvent()` should be coming from the `events_pb2.py` that you've generated from:
```shell
protoc --proto_path="<LiveAPI directory>" --python_out="<target directory>" events.proto
```
https://apexliveapi.com/docs/quickstart/python/#preparing-to-use-protobuf

Let me know if it's still being weird, I'll be happy to continue investigating for you.

**Comment by HarryOYY** [comment]
The websockets highlighting was just because I had VS code in restricted mode it looks like. After playing with it some more I realized I was never even getting the 'Connected!' print statement. I threw the 11-15 into the server script I had been using and it connects.

https://gist.github.com/HarryOYY/ea63bc1524f9a5ce6fa262c79d73c79e

**Comment by zeejayym** [comment]
Cool, are you getting responses from the game now?

**Comment by zeejayym** [comment]
Closing this due to no response.

If you have another issue, feel free to open up another one!
